name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.8","3.7","3.7.1","3.7.8","3.8.1","3.8.8","3.9.1","3.9.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip && pip install -r requirements.txt -r requirements-dev.txt
    - name: Analysing the code with pylint
      run: |
        pylint concordat/interface.py
    # - name: Analysing the code with black
    #   run: black --check concordat/
    - name: Ensure MyPy passes
      run: mypy concordat/interface.py
    - name: Run Pytest
      run: pytest concordat/interface_test.py

